import React from 'react';
import SparkSection from './SparkSection';
import AchievementSummary from './AchievementSummary';
import CertificateSection from './CertificateSection';

const ReportPreview = ({ reportData }) => {
  const sparkSections = [
    {
      title: 'Situation Analysis',
      icon: 'Search',
      content: reportData?.sparkResponses?.situation
    },
    {
      title: 'Strategic Planning',
      icon: 'Target',
      content: reportData?.sparkResponses?.plan
    },
    {
      title: 'Action Implementation',
      icon: 'Play',
      content: reportData?.sparkResponses?.action
    },
    {
      title: 'Reflection & Learning',
      icon: 'MessageCircle',
      content: reportData?.sparkResponses?.reflection
    },
    {
      title: 'Knowledge Integration',
      icon: 'BookOpen',
      content: reportData?.sparkResponses?.knowledge
    }
  ];

  return (
    <div className="bg-card border border-border rounded-lg overflow-hidden">
      {/* Report Content */}
      <div className="p-8 space-y-8">
        {/* Mission Overview */}
        <div className="text-center pb-6 border-b border-border">
          <h2 className="text-3xl font-bold text-foreground mb-2">
            {reportData?.missionTitle}
          </h2>
          <p className="text-lg text-muted-foreground mb-4">
            Innovation Report & Learning Artifact
          </p>
          <div className="flex flex-wrap justify-center gap-4 text-sm text-muted-foreground">
            <span>Completed: {reportData?.completionDate}</span>
            <span>•</span>
            <span>Duration: {reportData?.missionDuration}</span>
            <span>•</span>
            <span>Methodology: SPARK Framework</span>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="bg-muted/50 rounded-lg p-6">
          <h3 className="text-xl font-semibold text-foreground mb-3">Executive Summary</h3>
          <p className="text-foreground leading-relaxed">
            {reportData?.executiveSummary}
          </p>
        </div>

        {/* SPARK Sections */}
        <div>
          <h3 className="text-xl font-semibold text-foreground mb-6">SPARK Methodology Implementation</h3>
          {sparkSections?.map((section, index) => (
            <SparkSection
              key={index}
              title={section?.title}
              icon={section?.icon}
              content={section?.content}
              index={index}
            />
          ))}
        </div>

        {/* Achievement Summary */}
        <AchievementSummary
          achievements={reportData?.achievements}
          streakData={reportData?.streakData}
          skillsGained={reportData?.skillsGained}
        />

        {/* Certificate */}
        <CertificateSection
          certificateId={reportData?.certificateId}
          missionTitle={reportData?.missionTitle}
          learnerName={reportData?.learnerName}
          completionDate={reportData?.completionDate}
          validationCode={reportData?.validationCode}
        />

        {/* Footer */}
        <div className="text-center pt-6 border-t border-border text-sm text-muted-foreground">
          <p>Generated by NeuroSparkED Innovation Platform</p>
          <p>Report ID: {reportData?.reportId} | Generated: {new Date()?.toLocaleString()}</p>
        </div>
      </div>
    </div>
  );
};

export default ReportPreview;